# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARFighter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARFighter
  pod 'SwiftSocket'
  #pod 'JSONCodable', '~>3.0.1'
  #pod 'Cereal', '~> 4.0'
  pod 'ObjectMapper', '~> 3.1'
end
